name: Deploy

on:
    push:
        branches: ["main"]
    schedule:
        - cron: "0 6 * * *"
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    pipes:
        uses: dragunovartem99/pipes/.github/workflows/deploy.yaml@main
        with:
            build-command: build
            dist-folder: ./dist
        secrets:
            build-env: '{"GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"}'
